Update Post Relationships
MLH-Fellowship/SocioMark pull request #11
Opened 2021-03-30 13:48 UTC by aitikgupta

Only Creating `/post/create` a post will not require a user id, all other endpoints will need an ID due to a one-to-many relationship.

2021-03-30 15:05 UTC, bodhisha requested changes

2021-03-30 15:05 UTC, bodhisha commented on backend/app/server/controllers/user.py
> +    print("author:", user_id, "post:", post_id)
Can remove the print statement right..

2021-03-30 15:05 UTC, bodhisha commented on backend/app/server/routes/post.py
>  @router.post("/create", response_description="Post added into the database")
Now the route is returning status code 200 which is "OK". It is more preferable to return status code 201 which indicates successfully created

2021-03-30 15:15 UTC, aitikgupta commented on backend/app/server/controllers/user.py
> +    print("author:", user_id, "post:", post_id)
woops. will fix XD

2021-03-30 15:16 UTC, aitikgupta commented on backend/app/server/routes/post.py
>  @router.post("/create", response_description="Post added into the database")
Makes sense, will update

2021-03-30 16:09 UTC, aitikgupta commented on backend/app/server/controllers/user.py
> +    print("author:", user_id, "post:", post_id)
Done

2021-03-30 16:09 UTC, aitikgupta commented on backend/app/server/routes/post.py
>  @router.post("/create", response_description="Post added into the database")
Done 👍🏼

2021-03-30 16:11 UTC, DebugAgrawal approved these changes

2021-03-30 16:11 UTC, DebugAgrawal approved these changes

2021-03-30 16:14 UTC, merged

2021-03-31 15:48 UTC, bodhisha reviewed
LGTM