allow users to edit post
MLH-Fellowship/SocioMark pull request #119
Opened 2021-04-15 07:35 UTC by suhanichawla

User can click on pencil icon in front of post description to edit it. User can click on check icon to complete editing. Relevant error and success toasts are displayed.
Attaching screenshots for reference. 

Editable description
![Screenshot (298)](https://user-images.githubusercontent.com/44273715/114831257-cc464f00-9dea-11eb-8125-3a00b3525c4a.png)

Toast displayed
![Screenshot (299)](https://user-images.githubusercontent.com/44273715/114831360-ebdd7780-9dea-11eb-89e0-bbefff48ccf0.png)

Edit icon
![Screenshot (300)_LI](https://user-images.githubusercontent.com/44273715/114831500-14657180-9deb-11eb-9852-4a4633e99c67.jpg)

2021-04-15 08:00 UTC, aitikgupta commented
All checks fail to start because the `greetings bot` itself fails due to a long-known issue https://github.com/actions/first-interaction/issues/10
The best way to deal with this would be to remove the bot, since we definitely need the linter actions to do their job.

Ping @bodhisha @DebugAgrawal to make this executive decision.

2021-04-15 08:13 UTC, aitikgupta requested changes
In general, amazingg work @suhanichawla 🎉 
We don't have linter checks running on this PR atm, reviewed it anyway.

(you get browny points for fixing the FastAPI endpoint)

2021-04-15 08:13 UTC, aitikgupta commented on backend/app/server/controllers/post.py
> +        with tempfile.NamedTemporaryFile(delete=False,suffix=".png") as tmp:
```suggestion
        with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as tmp:
```

2021-04-15 08:13 UTC, aitikgupta commented on backend/app/server/controllers/post.py
> +            {"_id": ObjectId(post_id)}, {"$set": data}
ahaha thanks for this^

2021-04-15 08:13 UTC, aitikgupta commented on backend/app/server/models/post.py
> +    post_id: str
Python suggests optional parameters to exist after the required parameters.
(example: `def func(req_param, optional_param = None)`)
```suggestion
    post_id: str
    description: Optional[str]
```

2021-04-15 08:13 UTC, aitikgupta commented on backend/app/server/routes/post.py
> +    return ResponseModel(new_post,"Post updated successfully.")
I'm basically doing a Flake8 manual check atm. xD
```suggestion
    return ResponseModel(new_post, "Post updated successfully.")
```

2021-04-15 08:13 UTC, aitikgupta commented on frontend/package-lock.json
>      "binary-extensions": {
Do we need to make changes to `package-lock`?
We're not adding/removing a dependency in this PR are we?

I believe this is a mismatch between user's preinstalled packages and the repo's. (ping @bodhisha that's what I meant when I said package-lock is a mess xD)

2021-04-15 08:22 UTC, bodhisha requested changes
@suhanichawla  Thanks for checking out the issues. PR looks good..!🎉 A small suggestion from my part, currently the description is editable by every user in the system (though not possible from the backend). So If you could show the `edit icon` only to the `post owners`, it would be cool..

2021-04-15 09:27 UTC, suhanichawla commented
> @suhanichawla Thanks for checking out the issues. PR looks good..!🎉 A small suggestion from my part, currently the description is editable by every user in the system (though not possible from the backend). So If you could show the `edit icon` only to the `post owners`, it would be cool..

Completely slipped my mind, fixed this now, thanks!

2021-04-15 09:28 UTC, suhanichawla commented
> In general, amazingg work @suhanichawla 🎉
> We don't have linter checks running on this PR atm, reviewed it anyway.
> 
> (you get browny points for fixing the FastAPI endpoint)
> 
> Netlify deployed URL: https://6077ecb8193d2e000830a477--sociomark.netlify.app/
> (it doesn't show up here because of the failing checks)

Committed all the indentation fixes

2021-04-15 09:35 UTC, aitikgupta commented
Good news: Greetings bot is working fine now, via #120 

Bad news: Why are linters not running their checks? :/

2021-04-15 09:43 UTC, aitikgupta commented
@suhanichawla you're our first PR which isn't from one of the authors, and which is why we're running into so many issues with those actions.
Just wanted to thank you for your patience, we'll try to fix those soon. :)

2021-04-16 10:19 UTC, aitikgupta commented
@suhanichawla can you rebase to main?
Linters oughta be running now. (also the merge conflict)

2021-04-16 14:31 UTC, aitikgupta approved these changes
This is good to go! 🎉

2021-04-16 15:09 UTC, bodhisha approved these changes

2021-04-16 15:10 UTC, merged

2021-04-16 15:11 UTC, aitikgupta commented
@suhanichawla thanks for your contribution! (and for the patience handling the linters :p)