Added delete post functionality
MLH-Fellowship/SocioMark pull request #129
Opened 2021-04-15 15:39 UTC by DebugAgrawal

> ### Now user can delete their own post 🚩

![image](https://user-images.githubusercontent.com/64848982/114897299-b8bcd780-9e2e-11eb-9a47-2e1ba3213065.png)

2021-04-15 16:15 UTC, aitikgupta commented
Can we do a X icon instead of "DELETE"? @bodhisha your css skillz needed. XD

2021-04-15 16:34 UTC, bodhisha reviewed
> Can we do a X icon instead of "DELETE"? @bodhisha your css skillz needed. XD

Yup yup. I think a small 🗑️ icon in red color would also look good with the UI? Text seems bit large with other icons

2021-04-15 18:06 UTC, DebugAgrawal commented
> > Can we do a X icon instead of "DELETE"? @bodhisha your css skillz needed. XD
> 
> Yup yup. I think a small 🗑️ icon in red color would also look good with the UI? Text seems bit large with other icons

🗑️ icon sounds good

2021-04-16 04:52 UTC, bodhisha requested changes
Looks good! 🎉 Just a suggestion to change the URL back to `http://localhost:8000`

2021-04-16 04:52 UTC, bodhisha commented on frontend/src/constants.js
> +    BASE_URL = "https://sociomark-backend.herokuapp.com";
By mistake right? @DebugAgrawal

2021-04-16 05:46 UTC, aitikgupta approved these changes
Awesomeee! 🎉

2021-04-16 05:55 UTC, bodhisha approved these changes

2021-04-16 05:56 UTC, merged